"""add sentiments table

Revision ID: 32a6a15ed0d2
Revises: 1691c8174801
Create Date: 2026-05-30 12:58:46.868305

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32a6a15ed0d2"
down_revision: str | None = "1691c8174801"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sentiments",
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("p_positive", sa.Float(), nullable=False),
        sa.Column("p_neutral", sa.Float(), nullable=False),
        sa.Column("p_negative", sa.Float(), nullable=False),
        sa.Column("confident", sa.Boolean(), nullable=False),
        sa.Column(
            "analyzed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_sentiments_post_id_posts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("post_id", name=op.f("pk_sentiments")),
    )
    op.create_index("ix_sentiments_label", "sentiments", ["label"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sentiments_label", table_name="sentiments")
    op.drop_table("sentiments")
    # ### end Alembic commands ###
