"""week1 initial schema (models, posts, post_models)

Revision ID: 5099a2f34ecc
Revises:
Create Date: 2026-05-29 15:43:37.185081

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5099a2f34ecc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("company", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column(
            "aliases",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
        sa.UniqueConstraint("slug", name=op.f("uq_models_slug")),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("subreddit", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("permalink", sa.Text(), nullable=True),
        sa.Column("flair", sa.Text(), nullable=True),
        sa.Column("over_18", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("score", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("num_comments", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("quality_score", sa.Integer(), nullable=True),
        sa.Column(
            "quality_flags",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("dq_processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_posts")),
        sa.UniqueConstraint("source", "external_id", name="uq_posts_source_external_id"),
    )
    op.create_index(
        "ix_posts_dq_unprocessed",
        "posts",
        ["fetched_at"],
        unique=False,
        postgresql_where=sa.text("dq_processed_at IS NULL"),
    )
    op.create_index("ix_posts_posted_at", "posts", ["posted_at"], unique=False)
    op.create_index("ix_posts_quality_score", "posts", ["quality_score"], unique=False)
    op.create_table(
        "post_models",
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["models.id"],
            name=op.f("fk_post_models_model_id_models"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["post_id"], ["posts.id"], name=op.f("fk_post_models_post_id_posts"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("post_id", "model_id", name=op.f("pk_post_models")),
    )
    op.create_index("ix_post_models_model_id", "post_models", ["model_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_post_models_model_id", table_name="post_models")
    op.drop_table("post_models")
    op.drop_index("ix_posts_quality_score", table_name="posts")
    op.drop_index("ix_posts_posted_at", table_name="posts")
    op.drop_index(
        "ix_posts_dq_unprocessed",
        table_name="posts",
        postgresql_where=sa.text("dq_processed_at IS NULL"),
    )
    op.drop_table("posts")
    op.drop_table("models")
    # ### end Alembic commands ###
